### ISSUE TITLE
Correct lexical `this` in exposed methods

### ISSUE THREAD

**Issue by kennedyrose** [smarterlabs/ulysses#15]
```
    TypeError: Cannot read property 'createEventType' of undefined

      51 |     key: "addEventListener",
      52 |     value: function addEventListener(on, fn) {
    > 53 |       this.createEventType(on);
         |            ^
      54 |       this.eventListeners[on].push(fn);
      55 |     }
      56 |   }, {

      at ael (packages/core/dist/index.js:53:12)
      at Object.<anonymous> (packages/core/__tests__/index.js:74:3)
```

**Comment by kennedyrose** [comment]
Bind in constructor?
